### ISSUE TITLE
lil nitpick, laravel docs link isn't evergreen

### ISSUE THREAD

**Issue by bradders** [bentonow/bento-laravel-sdk#6]
https://github.com/bentonow/bento-laravel-sdk/blob/bc5c8e8fb5498283fd85a780c1a50be5287a834d/README.md?plain=1#L53

Just noticed in passing that this link points to old 9x docs, the url without a version number should be self-healing: https://laravel.com/docs/mail

**Comment by jessehanley** [comment]
@bradders 😆
